import time

input("helo wot is ur problm?: ")
input("ok, enter yur bank acouent passowrd to start: ")
print("fixing...")
print("10%")
time.sleep(0.1)
print("20%")
time.sleep(0.1)
print("30%")
time.sleep(0.1)
print("40%")
time.sleep(0.1)
print("50%")
time.sleep(0.1)
print("60%")
time.sleep(0.1)
print("70%")
time.sleep(0.1)
print("80%")
time.sleep(0.1)
print("90%")
time.sleep(0.1)
print("100%")
time.sleep(0.1)
input("yur probelm is fixd. ")
